# Generated by Django 4.0.8 on 2024-08-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isCoach',
            field=models.BooleanField(default=False),
        ),
    ]
