# Generated by Django 4.0.8 on 2024-08-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_iscoach'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialism',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
